/* Auto-generated by tools/png_to_tiles.py from assets/sprites/beam.png -- do not edit manually */
#pragma bank 255
#include <stdint.h>
#include "banking.h"

/* Bank reference: BANKREF(name) emits a CODE stub; bankpack rewrites
   ___bank_name to the actual assigned bank at link time.
   Required for autobank (255) so BANK(name) returns the real bank. */
BANKREF(beam_tile_data)

const uint8_t beam_tile_data[] = {
    /* tile 0 */ 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    /* tile 1 */ 0xC3, 0xE7, 0xC3, 0xE7, 0xC3, 0xE7, 0xC3, 0xE7, 0xC3, 0xE7, 0xC3, 0xE7, 0xC3, 0xE7, 0xC3, 0xE7,
};

const uint8_t beam_tile_data_count = 2u;
