/* Auto-generated by tools/png_to_tiles.py from assets/sprites/bullet.png -- do not edit manually */
#pragma bank 255
#include <stdint.h>
#include "banking.h"

/* Bank reference: BANKREF(name) emits a CODE stub; bankpack rewrites
   ___bank_name to the actual assigned bank at link time.
   Required for autobank (255) so BANK(name) returns the real bank. */
BANKREF(bullet_tile_data)

const uint8_t bullet_tile_data[] = {
    /* tile 0 */ 0x00, 0x00, 0x00, 0x00, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x00, 0x00, 0x00, 0x00,
};

const uint8_t bullet_tile_data_count = 1u;
