/* Auto-generated by tools/png_to_tiles.py from assets/sprites/overmap_car.png -- do not edit manually */
#pragma bank 255
#include <stdint.h>
#include "banking.h"

/* Bank reference: BANKREF(name) emits a CODE stub; bankpack rewrites
   ___bank_name to the actual assigned bank at link time.
   Required for autobank (255) so BANK(name) returns the real bank. */
BANKREF(overmap_car_tile_data)

const uint8_t overmap_car_tile_data[] = {
    /* tile 0 */ 0x18, 0x18, 0x3C, 0x3C, 0x7E, 0x7E, 0xDB, 0xDB, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18,
    /* tile 1 */ 0x10, 0x10, 0x30, 0x30, 0x7F, 0x7F, 0xFF, 0xFF, 0x7F, 0x7F, 0x30, 0x30, 0x10, 0x10, 0x00, 0x00,
};

const uint8_t overmap_car_tile_data_count = 2u;
