#ifndef TRACK_H
#define TRACK_H

#include <gb/gb.h>
#include <stdint.h>
#include "config.h"

/* Terrain tile types — uint8_t, NOT typedef enum (SDCC makes enums 16-bit) */
typedef uint8_t TileType;
#define TILE_WALL   0u
#define TILE_ROAD   1u
#define TILE_SAND   2u
#define TILE_OIL    3u
#define TILE_BOOST  4u
#define TILE_FINISH 6u

/* Map type constants — emitted by tmx_to_c.py as track_map_type in generated files */
#define TRACK_TYPE_RACE   0u
#define TRACK_TYPE_COMBAT 1u

TileType track_tile_type_from_index(uint8_t tile_idx) BANKED;
TileType track_tile_type(int16_t world_x, int16_t world_y) BANKED;

extern const uint8_t track_tile_data[];
extern const uint8_t track_tile_data_count;
extern const int16_t track_start_x;
extern const int16_t track_start_y;
extern const uint8_t track_map[];
extern const uint8_t track2_map[];
extern const int16_t track2_start_x;
extern const int16_t track2_start_y;

/* Runtime track dimensions — set by load_track_header() at track_select() time.
 * These replace the former compile-time MAP_TILES_W / MAP_TILES_H constants. */
extern uint8_t active_map_w;
extern uint8_t active_map_h;

#include "checkpoint.h"
#include "banking.h"
#include "loader.h"
BANKREF_EXTERN(track_map)
BANKREF_EXTERN(track_tile_data)
BANKREF_EXTERN(track_start_x)
BANKREF_EXTERN(track_start_y)
BANKREF_EXTERN(track2_map)
BANKREF_EXTERN(track2_start_x)
BANKREF_EXTERN(track_map_type)
BANKREF_EXTERN(track2_map_type)
BANKREF_EXTERN(track3_map_type)

/* Per-track NPC spawn arrays — generated by tools/tmx_to_c.py --emit-header */
#include "track_npc_externs.h"

uint8_t track_get_id(void) BANKED;

/* Checkpoint ROM tables — emitted by tmx_to_c.py into track_map.c / track2_map.c */
extern const CheckpointDef track_checkpoints[];
extern const uint8_t        track_checkpoint_count;
extern const CheckpointDef track2_checkpoints[];
extern const uint8_t        track2_checkpoint_count;

/* Map type for each track — emitted by tmx_to_c.py into track[N]_map.c */
extern const uint8_t track_map_type;
extern const uint8_t track2_map_type;
extern const uint8_t track3_map_type;

/* --- TrackDesc dispatch table --- */

/* Per-track ROM descriptor. Pointer fields reference extern consts from generated map files.
 * Pointer initializers are used because extern const values are not C integer constant
 * expressions and cannot appear directly in static struct initializers. */
typedef struct {
    const uint8_t  *map;        /* raw map data including 2-byte header */
    const int16_t  *start_x;
    const int16_t  *start_y;
    uint8_t         lap_count;
    const uint8_t  *map_type;   /* points to track_map_type / track2_map_type / track3_map_type */
    uint16_t        reward;     /* scrap payout; TRACK1_REWARD / TRACK2_REWARD from config.h */
    /* load_tiles removed: tiles loaded by loader_load_state() */
} TrackDesc;

/* Select active track before entering STATE_PLAYING.
 * Must be called from bank-0 code (state_overmap.c) via the BANKED trampoline. */
void track_select(uint8_t id) BANKED;

/* Accessors — read from active TrackDesc */
uint8_t  track_get_lap_count(void) BANKED;
uint8_t  track_get_map_type(void) BANKED;
int16_t  track_get_start_x(void) BANKED;
int16_t  track_get_start_y(void) BANKED;
uint16_t track_get_reward(void) BANKED;

const CheckpointDef *track_get_checkpoints(void) BANKED;
uint8_t              track_get_checkpoint_count(void) BANKED;

void    track_init(void) BANKED;
uint8_t track_passable(int16_t world_x, int16_t world_y) BANKED;

/* Returns the raw tile index at world tile position (tx, ty).
 * BANKED — trampoline handles cross-bank dispatch safely. */
uint8_t track_get_raw_tile(uint8_t tx, uint8_t ty) BANKED;

/* Fills buf[0..active_map_w-1] with raw tile indices for world tile row ty.
 * Zeros buf on OOB ty. One BANKED call replaces 20 serial track_get_raw_tile()
 * calls in camera stream_row — reduces VBlank overrun risk. */
void track_fill_row(uint8_t ty, uint8_t *buf) BANKED;

/* Fills buf[0..count-1] with raw tile indices for columns tx_start..tx_start+count-1
 * of world tile row ty. Zeros buf entries for any OOB tile. BANKED. */
void track_fill_row_range(uint8_t ty, uint8_t tx_start, uint8_t count, uint8_t *buf) BANKED;

/* Fills buf[0..count-1] with raw tile indices for rows ty_start..ty_start+count-1
 * of world tile column tx. Zeros buf entries for any OOB tile. BANKED. */
void track_fill_col(uint8_t tx, uint8_t ty_start, uint8_t count, uint8_t *buf) BANKED;

#ifndef __SDCC
/* Test-only seam: inject a synthetic map without hardware (gcc host tests only).
 * Never compiled into the GB ROM. */
void track_test_set_map(const uint8_t *map, uint8_t w, uint8_t h);
#endif

#endif /* TRACK_H */
