/* generated by png_to_tiles.py — do not edit */
#ifndef TRACK_TILESET_META_H
#define TRACK_TILESET_META_H
#define TRACK_TILE_LUT_LEN 26u
static const uint8_t track_tile_type_lut[TRACK_TILE_LUT_LEN] = {
    TILE_WALL,  /* 0 */
    TILE_ROAD,  /* 1 */
    TILE_ROAD,  /* 2 */
    TILE_WALL,  /* 3 */
    TILE_ROAD,  /* 4 */
    TILE_ROAD,  /* 5 */
    TILE_SAND,  /* 6 */
    TILE_ROAD,  /* 7 */
    TILE_OIL,  /* 8 */
    TILE_ROAD,  /* 9 */
    TILE_BOOST,  /* 10 */
    TILE_ROAD,  /* 11 */
    TILE_FINISH,  /* 12 */
    TILE_ROAD,  /* 13 */
    TILE_ROAD,  /* 14 */
    TILE_ROAD,  /* 15 */
    TILE_ROAD,  /* 16 */
    TILE_ROAD,  /* 17 */
    TILE_ROAD,  /* 18 (rotated from 9) */
    TILE_ROAD,  /* 19 (rotated from 9) */
    TILE_ROAD,  /* 20 (rotated from 9) */
    TILE_WALL,  /* 21 (rotated from 10) */
    TILE_WALL,  /* 22 (rotated from 10) */
    TILE_WALL,  /* 23 (rotated from 10) */
    TILE_WALL,  /* 24 (rotated from 10) */
    TILE_WALL,  /* 25 (rotated from 10) */
};
#endif /* TRACK_TILESET_META_H */
