/* Auto-generated by tools/png_to_tiles.py from assets/sprites/turret.png -- do not edit manually */
#pragma bank 255
#include <stdint.h>
#include "banking.h"

/* Bank reference: BANKREF(name) emits a CODE stub; bankpack rewrites
   ___bank_name to the actual assigned bank at link time.
   Required for autobank (255) so BANK(name) returns the real bank. */
BANKREF(turret_tile_data)

const uint8_t turret_tile_data[] = {
    /* tile 0 */ 0x18, 0x18, 0x18, 0x18, 0x18, 0x24, 0xE7, 0xD3, 0xE7, 0xCB, 0x18, 0x24, 0x18, 0x18, 0x18, 0x18,
};

const uint8_t turret_tile_data_count = 1u;
